/*******************************************************
Project : Greenhouse
Version : 0.0
Date    : 07.10.2022
Chip type               : ATmega32
Program type            : Application
Clock frequency     : 16 MHz
Programm size       : 11358 words (22716 bytes), 69,3% of FLASH 11.09.2022
*******************************************************/

#include <mega32.h>
#include <stdio.h>
#include <twi.h>
#include <delay.h>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <1wire.h>
#include "fontsN.h"
#include "tft.h"
#include "9341.h"
//*********************************
#define CSDAC1		    PORTD.4
#define CSDAC2		    PORTD.5
#define CSDAC3		    PORTD.6
#define CSDAC4	        PORTD.7
#define CONECT          PINB.3    // если bluetooth подключен то здесь +3,3В
#define MAX_DEVICES     3
#define MAX_MENU        5
#define MAX_SET         4
#define MAX_DATE        5

#define ON              1
#define OFF             0
#define UNCHANGED       2
#define MISTAKE         3
#define ZERO	        50

#define SBLK		    0x91      // Начало блока данных
#define BSTR		    0x81      // Начало строки данных
#define EBLK            0xF1      // Конец блока данных
#define DS3231          0xD0      // Часовая микросхема

#define SPI_MOUD_FL	    0x51	  // SPI Type: Master, Clock Rate: 1000,000 kHz, Clock Phase: Cycle Half, Clock Polarity: Low, Data Order: MSB First
#define TWI_CLK_RATE    100000    // TWI clock rate [bps]
#define EEPROM_TWI_BUS_ADDRESS (0xA0 >> 1)// 7 bit TWI bus slave address of the AT24C16B 2kbyte EEPROM
#define ADC_VREF_TYPE   0x40

// Declare your global variables here
unsigned char BeepT, displ_num, portOut, newSetButt, ds18b20, pointY, DHTexist, signchar, intval, frcval, error;
signed char numMenu, numSet/*, displCO2, timerCO2*/;
unsigned char relOut[4]={0}, analogOut[4]={0}, dacU[4]={ZERO}, buff[40], familycode[MAX_DEVICES][9], clock_buffer[7], alarm[4]={2,2,2,2};
unsigned int  max_X, max_Y, fillScreen = BLACK;
signed int pvT=1990, offsetT, pvRH=1990, offsetRH, pvCO2, pvPH, newval[MAX_DATE];
unsigned char *ptr_char;
const char* setMenu[MAX_MENU]={"Температура","Влажность","Таймер","Настройки","Время и Дата"};
const char* setName0[MAX_SET]={"Задание","Отклон.","Гистер.","Режим"};
const char* setName1[MAX_SET]={"Включен","Выключен", "Размерн.","Шаг"};
const char* setName2[MAX_SET]={"Корекция Т","Корекция Вл","Датчик Вл","Резерв"};
const char* setName3[MAX_DATE]={"минуты","часы","день","месяц","год"};
//--------------- union declaration -----------------------------------------------
union {signed int point[MAX_DEVICES]; unsigned char buff[];} t; // буффер значений температур
union {unsigned char buffer[8]; unsigned int pvT;} ds;          // буффер микросхемы DS18B20
union {unsigned char buffer[4]; unsigned int val[2];} in;
union {unsigned char buffer[4]; unsigned int val[2];} out;
//---------------------------------------------------------------------------------
signed char analog[4]={-1,30,90,-1};
signed char relay[4]={2,2,2,2};
float Told1[5], Told2[5];

//-------------------------
eeprom signed int set[5][4]={
                     {270,10, 5, 0},  // Tset; dTalarm; hysteresis;  mode=0 -> нагрев / mode=1 -> охлаждение;
                     { 55, 5, 5, 0},  // RHset; dRHalarm; hysteresis;  mode=0 -> увлажнение / mode=1 -> осушение;
                     {250, 8, 4, 0},  // Tset; dTalarm; hysteresis;  mode=0 -> увлажнение / mode=1 -> осушение;
                     {  5,10, 1, 0},  // tmOn; tmOff; dimension=0 -> секунды / direction=1 -> минуты; dimension=0 -> секунды / direction=1 -> минуты;;
                     {  0, 0, 0, 0}}; // корекция датчика T; корекция датчика Вл; тип датчика = 0 -> DHT21; Other = 1 -> DHT11

bit Sec;
bit Clock_Ok;
bit Dht;
bit Soil;
bit pHsensor;
bit typeS;
bit CO2module;          // подключен измеритель СО2
bit CheckCO2;           // разрешено использование данных измерителя СО2

//- prototypes ------


#include "fontsN.c"
#include "ili9341.c"
#include "twi.c"
#include "dht.c"
#include "buttons.c"
#include "proc.c"
#include "control.c"
#include "touchpad.c"
#include "displ.c"

// External Interrupt 0 service routine
interrupt [EXT_INT0] void ext_int0_isr(void){
 static unsigned int count1;
 count1++;
}
// 0.25 Hz timer interrupt generated by Timer1 overflow;  Timer Period: 4,1943 s
interrupt [TIM1_OVF] void timer_comp_isr(void){
 Sec=1;
} 


void main(void){
// Declare your local variables here
char byte;
#include "init.c"

while (1){
   //----------- функция 1 секунда ---------------------------
   if(Sec){                     
     Sec=0; 
     if(ds18b20) temperature_check();
     if(Dht){                                         // присутствует датчик влажности
       if(readDHT()) DHTexist = 3; 
       else if(DHTexist) DHTexist--;                   // датчик влажности работает? 
       else {pvT = 1900; pvRH = 190;}
     }
     for(byte=0; byte<4; byte++){if(relay[byte]<2) relOut[byte]=relay[byte];}
     for(byte=0; byte<4; byte++){
        if(analog[byte]>=0) analogOut[byte] = analog[byte]; else analogOut[byte] = 0; //??????????????
        dacU[byte] = adapt(analogOut[byte]);// конверсия для ЦАП
     }
 //    setDAC();                           // подать напряжение на аналоговые выходы
     // --------КАНАЛ 1 ---------
     if(Dht){
       RelayControl(pvT,0);
       RelayControl(pvRH,1);
     } 
     else {
       RelayControl(t.point[0],0);
       RelayControl(t.point[1],1);
     }
     // --------КАНАЛ 2 --------- 
//     relayHadl();
//     analogHadl();
//     if (displ_num<3) display();
//     //-- CO2 ----------------------------------
//     if(CO2module){
//       byte = readCO2();     // если модуль подключен то обмениваемся командами и обновляем только pvCO2
//       if(byte) pvCO2 = LowPassF2(pvCO2,3);// если идет измерение СО2 то обновляем Tf[3]
//       controlCompressorCO2(4);  // Компрессор СО2.
//     }
   }
   //---------------------------------------------------------
//   if(newButton==100) display();
//   else {touchpad(newButton); newButton=100; display();}
    display();
//   sprintf(buff,"X%4u; Y%4u; D%u newB=%3u",point_X,point_Y, displ_num, newButton);
//   ILI9341_WriteString(5,TFTBUTTON-10,buff,Font_11x18,WHITE,BLACK,1);
 }
}
